# Generated by Django 4.2.4 on 2023-09-11 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default='author', max_length=255),
            preserve_default=False,
        ),
    ]
